title: William M Seath
logo: "/images/el dude brothers.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My online portfolio space 
  <br><br>
  Please feel free to contact me via my email or LinkedIn 
  <br><br>
  <a href="https://www.linkedin.com/in/william-s-91a21a119/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
